version: "3.3"
services:
  spark-master:
    image: bigdatapoc/spark-jupyter:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-network
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"
      - "PYSPARK_SUBMIT_ARGS=--packages org.apache.spark:spark-avro_2.12:2.4.2 pyspark-shell"
    command: "/start-master.sh"
  spark-worker:
    image: bigdatapoc/spark-jupyter:latest
    depends_on:
      - spark-master
    ports:
      - 8080
    networks:
      - spark-network
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8080"
      - "PYSPARK_SUBMIT_ARGS=--packages org.apache.spark:spark-avro_2.12:2.4.2 pyspark-shell"
    command: "/start-worker.sh"
    volumes: # replace the mounted folder as you like
      - "D:/DevStudio/Docker/Project/Jupyter:/home/jovyan/work"
      
networks:
  spark-network:
    driver: bridge
    ipam:
      driver: default

     